### ISSUE TITLE
Is there a possibility for a higher-level, JS-like wrapper?

### ISSUE THREAD

**Issue by jefffriesen** [turbo/js#12]
This is a really neat project. Is there any way to create a javascript-friendly API that wraps things like this:
```js
`void main(void) {commit(read() * 4.}`
```
Maybe something like a very limited set of lodash functions that will work with this library.

I have needs for high-performance computing in the browser. But I also have to weigh the tradeoffs of learning and using something like GLSL vs. pure javascript. The reasons I may want to invest time in this are well laid out on your site. Here are some reasons why I may not want to invest time in this:
* Time for me to get up to speed
* There may be limitations that I don't know about yet that would end up sinking a lot of time but never deploy it
* Debugability
* Other developers coming after me to work on this code (or my future self who hasn't used it in a while)

A JS-like API would mostly remove these issues and likely greatly increase adoption. I think it would be worth it even if you could only expose a subset of useful functionality through the JS API. Then people could use the GLSL directly after they are already getting wins out of the library. 

Here are some related libs:
https://github.com/stackgl/glsl-transpiler (GLSL -> JS)
http://typedarray.org/shaderdsl-js-javascript-based-dsls-for-gpu-shaders/ (JS -> GLSL)
https://www.npmjs.com/package/glslify

It could even be a user-contributed library of functions where you pass in variables (or functions) and it passes back the GLSL code that is executed in your lib. 

If all this is a bad idea or technically difficult it would be interesting to know why. If it's a good idea but  no bandwidth to implement it, that's also helpful to know. I doubt I could contribute much since I have zero experience with GLSL but others watching this library may be able to contribute. 

Thanks - this looks really interesting.

**Comment by turbo** [comment]
Hi, thanks for your time writing this idea down in detail.

First, opinions:

I think GLSL is easy. Yes, it's C and typed (even more strictly on linux VGA drivers as it turns out), but for the task it is designed for, it couldn't be simpler. To someone who doesn't have experience with GLSL, the vector-oriented layout might seem daunting, but even for that, GLSL holds your hand with massively overloaded standard operators.

Members of the GPGPU community (and democoders ;-) ) have spent a great deal of time introducing canonical shorthands for common tasks, a good example would be the [random oneliner](http://stackoverflow.com/questions/12964279/whats-the-origin-of-this-glsl-rand-one-liner).

Only the set of narrow contracts that C gives you, enables you to truly optimize. This optimization is less important in turbo.js, but rather in it's C++ brother (which is not public). In order to make up for the overhead JS and WebGL create in general, you still need highly optimized code though.

I dare to say that anyone who comes from a strictly web background and learns GLSL pretty much instantly turns into a better programmer. Not only did you learn a new language, but a completely different architecture: a massively parallel one. Ready for Power8 ;-) ?

I fail to see how any abstract language can retain this amount of optimizability and yet still be less verbose. There have been experiments bringing other paradigms, an example would be [Shaderforth](https://github.com/daeken/Shaderforth).

The truth is that n steps before running something add n times the latency.

Now let me address your points:

**Time for me to get up to speed**

This a very divisive matter. I dare to claim that GLSL is really easy to learn. See above.

**Debugability**

GLSL has tremendously helpful debuggers. I actually tried to illustrate that with Example 3 of the walk-through. Of course, using transpilers that _target_ GLSL, this is retained, yet you also need to debug the language you create.

Take a scalar language like JS and make a subset that can be transpiled to GLSL. You still need to keep the vectorized architecture in mind. That would result in something like TypeScript or ECMA 4. From there it's just a small step to C anyway.

The overhead of creating such a language would far exceed the small time saved writing kernels in my book.

**So.**

Of course I could go on rambling about why I don't think that idea is worth doing, but I want to be more productive. Before I continue: If you want this: Do it! Create a proof of concept that shows a benefit in terms of time invested writing code. Maybe we can integrate this when turbo.js stabilizes.

Now here is my plan going forward:

While I don't think that transpiling to GLSL is a good idea, transpiling from GLSL to JS is a genius idea. You mentioned glsl-transpiler, which I also discussed in the readme. The idea is to write in GLSL and create an automatic fallback. So you wouldn't need to write a JS fallback yourself. In doing that, we effectively create a DIY (and way more portable) version of what Web**C**L will be.

As you might have read, turbo.js uses a specific high-bandwidth texture type (read memory layout) that isn't available on some devices, for example cheap Mali mobile GPUs. This is the issue that has to be solved first. I already have a workaround for this, I just need further testing.

After that is released, one can get an idea about what turbo.js will look like going into the future.

**Comment by wparad** [comment]
You aren't going to win any supporters by arguing an opinion.  Just because some people like C, does mean every does.  I think improving the API interface to using JS, is what people want, especially when we called the library turbojs.

**Comment by jefffriesen** [comment]
@turbo Thanks a lot for your response. While I do think that my bullet points are still valid concerns, I like hearing people advocate advantages of a language. For example, I heard many times that you will become a better programmer if you learn Clojure. I learned it and it was true. Also I have learned C (admittedly a long time ago) and other languages. So my reasons for having a JS api isn't just because I'm coming from a web background. 

Having a pure JS option for common operations (I think) is an easier entry into a library than requiring GLSL right off the bat. Then allow people to drop down to GLSL if the common operations aren't enough. All of your well laid out arguments for GLSL then still apply to people who want to go further. 

For a glsl-to-js approach, it could be something like compiling this GLSL code to JS:

``` c
// compile to the js function `inputMultiply`
void main(int num) { 
   commit(read() * num); 
} 
```

Then it could be used like this from your original example:

``` js
import {inputMultiply} from 'glsl-js-contrib'

// Test if turbo.js is available 
if (turbojs) { 
  // Allocate a float-array of size 1,000,000 
  var blah = turbojs.alloc(1e6); 

  // Initialize data 
  for (i = 0; i <= 1e6; i++) blah.data[i] = i; 

  // [0, 1, 2, 3, 4] 
  console.log(blah.data.subarray(0, 5)); 

  // A simple kernel that calculates input *= 4 
  // for all 1e6 floats in parallel 
  // turbojs.run(blah, `void main(void) { 
  //   commit(read() * 4.); 
  // }`); 
  turbojs.run(blah, inputMultiply(4)); 

  // [0, 4, 8, 12, 16] 
  console.log(blah.data.subarray(0, 5)); 

  // That's it :-) 
} 
```

It's just an idea. Either way it's appropriate to close this ticket.  Thanks
